version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres-container
    ports:
      - "${PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_DB: "${DATABASE}"
    volumes:
      - DbData:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "${PGADMIN_PORT:-80}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    volumes:
      - pgAdminData:/var/lib/pgadmin

volumes:
  DbData:
  pgAdminData: